### ISSUE TITLE
Thoughts on per-site settings

### ISSUE THREAD

**Issue by kizu** [pepelsbey/add-to-things#1]
It would be nice to have a way of controlling where each new task goes based on different things like page's url and its title.

How I see it: there can be settings, where you could add a “filter rule” with conditions and effects.

There could be multiple conditions, each is a regexp check for either url or title.

The effects could be:

- Adding specific tags.
- Moving the task to a project and/or Area.
- Changing the given title/url parts based on regexp.

etc.

**Comment by pepelsbey** [comment]
You could help to move this task forward by testing Things API: what keys are available and exactly it would be possible to pass desired information. You can test it by running `open 'things:add?title=foo&notes=bar'` in console.
