### ISSUE TITLE
Doesn't seem to work with the new Things release

### ISSUE THREAD

**Issue by anthonysapien** [pepelsbey/add-to-things#10]
I have Things 3.1 installed, and pressing the extension icon has no effect. No dialog appears, and the URL is not added to Things. Thanks!

**Comment by pepelsbey** [comment]
Hmm, WFM

![image](https://user-images.githubusercontent.com/105274/28029291-37912f70-65a8-11e7-878b-f708d719d6e9.png)

![image](https://user-images.githubusercontent.com/105274/28029310-45e38eec-65a8-11e7-9662-709b01fb27ec.png)

What’s the version of your extension? See `chrome://extensions`, it should be 1.3.0.

**Comment by anthonysapien** [comment]
Hi, thanks for looking. When I press the button, the favicon on the tab
spins, but no dialog opens.

[image: image.png]
[image: image.png]

**Comment by pepelsbey** [comment]
What’s the version of your extension? See `chrome://extensions`, it should be 1.3.0.

**Comment by anthonysapien** [comment]
Sorry, those images didn't come through. My Chrome extension is 1.3.0, and Things Version 3.1 (30100506). I've tried removing the extension from Chrome and re-installing. I don't see any messages in the Web Developer Tools Console. Wish I could be of more help.
