### ISSUE TITLE
Busted in Chrome 49 (released today)

### ISSUE THREAD

**Issue by randallb** [pepelsbey/add-to-things#5]
Install chrome 49, install extension. Hit extension button, nothing happens.

**Comment by pepelsbey** [comment]
Confimed. Figuring out what went wrong.

**Comment by randallb** [comment]
Something with appurls is busted generally in chrome. Probably worth testing on beta / canary channels to see if it's fixed.

**Comment by kevinold** [comment]
I'm finding this works on some sites (literally https://samdutton.wordpress.com/2010/12/16/debugging-google-chrome-extensions/) but not on others like github.com or atlassian.net.

**Comment by randallb** [comment]
@pepelsbey would it make it easier if I cataloged sites it worked on and sites it was busted on?

**Comment by pepelsbey** [comment]
@randallb, I don’t think it would make any easier to find a proper solution. But I’m still experimenting with other methods of launching commands that might still work.

**Comment by kevinold** [comment]
I just updated to Chrome 50 on the release channel and this is still broken. :(  Any debugging attempts I've made have been unsuccessful to discover what the real issue is.

**Comment by randallb** [comment]
This might be fixed now? I've been using it and haven't seen issues as frequently.

**Comment by pepelsbey** [comment]
WFM in Chrome, still broken in Opera. Closing for now anyway.
