### ISSUE TITLE
Not in chrome store anymore

### ISSUE THREAD

**Issue by randallb** [pepelsbey/add-to-things#6]
Was it pulled? I love this extension. :)

**Comment by pepelsbey** [comment]
I unpublished it for now as it wasn’t working stable enough. I’ll be glad to publish it back once it’s fixed, but I’m not using it myself anymore. Are you willing to help?

**Comment by randallb** [comment]
Would love to help. Tell me how and I'm totally willing to.

**Comment by pepelsbey** [comment]
Thank you @randallb, you’re a collaborator now so you can freely push to the repository. There are 2 main tasks I see now:

1. Test the current version properly in Chrome and preferably in Opera as well
2. Reimplement selection functionality [I recently rolled back](https://github.com/pepelsbey/add-to-things/commit/59f76190e92cc1855b22fde143b9f725cde4d890) as it wasn’t working properly.

But feel free to do whatever you think might be useful for this extension. And once you think it’s stable enough I’ll put it back. Thank you again!

**Comment by randallb** [comment]
OK. I'm going to spend a little bit of downtime each week contributing. First: to get it running locally. :)

**Comment by kevinold** [comment]
Please test my fix #7 and let me know if it works for either of you.

**Comment by pepelsbey** [comment]
[…and it’s back](https://chrome.google.com/webstore/detail/add-to-things/bfbgliglkhckblibeiojndpncmahbmpo), with updated icon and faster response, thanks to @kevinold. Thank you for help guys!
